# Script to deploy on the REnder cloud platform
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} # This is github token
        service-id: "srv-cgcb8s02qv267uccbne0"
        retries: 20
        wait: 16000
        sleep: 30000
